# Generated by Django 4.0.5 on 2022-07-01 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
