# Generated by Django 3.2.13 on 2022-07-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_sentemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='sender',
            field=models.EmailField(default='jakeperaltab90@gmail.com', max_length=254),
        ),
    ]
